### ISSUE TITLE
Yaml file with additional coverage and notification

### ISSUE THREAD

**Issue by jperram92** [l-peacock/salesforce-project-template#4]
https://github.com/l-peacock/salesforce-project-template/blob/main/.github/workflows/pmd.yml

**Add Notifiers and Reporting**:

Add notifications or reports to alert developers when PMD scans produce findings, especially for critical violations or issues.
You can integrate a Slack or email notification step after the PMD scan is completed, for example, to notify developers of the results.

```
- name: Notify Slack of PMD Results
  uses: slackapi/slack-github-action@v1
  with:
    slack_token: ${{ secrets.SLACK_TOKEN }}
    channel: '#dev-alerts'
    text: "PMD scan completed. Check results for issues."

  schedule:
  - cron: '0 0 * * 1'  # Every Monday at midnight

```
